services:
    # ---------- FRONTEND ----------
    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        networks:
            - ecommerce

    # ---------- USER SERVICE ----------
    user_backend:
        build: ./backend/modules/user_backend
        volumes:
            - ./backend/modules/user_backend:/app
            - ./shared:/shared
        container_name: user_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - ecommerce

    # ---------- CATEGORY SERVICE ----------
    category_backend:
        build: ./backend/modules/category_backend
        volumes:
            - ./backend/modules/category_backend:/app
            - ./shared:/shared
        container_name: category_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - ecommerce

    # ---------- PRODUCT SERVICE ----------
    product_backend:
        build: ./backend/modules/product_backend
        volumes:
            - ./backend/modules/product_backend:/app
            - ./shared:/shared
        container_name: product_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - ecommerce

    # ---------- ORDER SERVICE ----------
    order_backend:
        build: ./backend/modules/order_backend
        volumes:
            - ./backend/modules/order_backend:/app
            - ./shared:/shared
        container_name: order_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - rabbitmq
        networks:
            - ecommerce

    # ---------- PAYMENT SERVICE ----------
    payment_backend:
        build: ./backend/modules/payment_backend
        volumes:
            - ./backend/modules/payment_backend:/app
            - ./shared:/shared
        container_name: payment_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - rabbitmq
        networks:
            - ecommerce

    # ---------- CART SERVICE ----------
    cart_backend:
        build: ./backend/modules/cart_backend
        volumes:
            - ./backend/modules/cart_backend:/app
            - ./shared:/shared
        container_name: cart_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        depends_on:
            - postgres
            - rabbitmq
        networks:
            - ecommerce

    # ---------- DATABASE ----------
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${USER_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - ecommerce
        ports:
            - '5432:5432'

    # ---------- CACHE ----------
    redis:
        image: redis:7
        container_name: redis
        restart: always
        networks:
            - ecommerce
        ports:
            - '6379:6379'

    # ---------- MESSAGE QUEUE ----------
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672' # Broker
            - '15672:15672' # Management UI
        networks:
            - ecommerce

    # ---------- REVERSE PROXY ----------
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - user_backend
            - category_backend
            - product_backend
            - order_backend
            - payment_backend
            - cart_backend
        networks:
            - ecommerce

networks:
    ecommerce:

volumes:
    postgres_data:
