services:
    # ---------- FRONTEND ----------
    frontend:
        build: ./frontend
        container_name: frontend
        restart: always
        networks:
            - ecommerce

    # ---------- USER SERVICE ----------
    user_backend:
        build: ./backend/user_backend
        volumes:
            - ./backend/user_backend:/app
        container_name: user_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - mysql
            - redis
            - rabbitmq
        networks:
            - ecommerce

    # ---------- PRODUCT SERVICE ----------
    product_backend:
        build: ./backend/product_backend
        volumes:
            - ./backend/product_backend:/app
        container_name: product_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - mysql
            - redis
            - rabbitmq
        networks:
            - ecommerce

    # ---------- ORDER SERVICE ----------
    order_backend:
        build: ./backend/order_backend
        volumes:
            - ./backend/order_backend:/app
        container_name: order_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - ecommerce

    # ---------- PAYMENT SERVICE ----------
    payment_backend:
        build: ./backend/payment_backend
        volumes:
            - ./backend/payment_backend:/app
        container_name: payment_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - ecommerce

    # ---------- CART SERVICE ----------
    cart_backend:
        build: ./backend/cart_backend
        volumes:
            - ./backend/cart_backend:/app
        container_name: cart_backend
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - ecommerce

    # ---------- DATABASE ----------
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} || Navithkumar2001@9
            # MYSQL_DATABASE: ${USER_DB} || ecommerce
            # MYSQL_USER: ${MYSQL_USER} || root
            MYSQL_ROOT_PASSWORD: Navithkumar2001@9
            MYSQL_DATABASE: ecommerce
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ecommerce
        ports:
            - '3307:3306'

    # ---------- CACHE ----------
    redis:
        image: redis:7
        container_name: redis
        restart: always
        networks:
            - ecommerce
        ports:
            - '6379:6379'

    # ---------- MESSAGE QUEUE ----------
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672' # Broker
            - '15672:15672' # Management UI
        networks:
            - ecommerce

    # ---------- REVERSE PROXY ----------
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - user_backend
            - product_backend
            - order_backend
            - payment_backend
            - cart_backend
        networks:
            - ecommerce

networks:
    ecommerce:

volumes:
    mysql_data:
