# Generated by Django 5.2.6 on 2025-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
