events {}

http {
    upstream frontend {
        server frontend:80;
    }

    upstream user-backend {
        server user-backend:8000;
    }

    upstream product-backend {
        server product-backend:8000;
    }

    upstream orders-backend {
        server orders-backend:8000;
    }

    upstream payment-backend {
        server payment-backend:8000;
    }

    upstream cart-backend {
        server cart-backend:8000;
    }

    upstream category-backend {
        server category-backend:8000;
    }

    server {
        listen 80;

        client_max_body_size 50M;

        # React frontend
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---------- API ROUTES ----------
        location /api/users/ {
            proxy_pass http://user-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products/ {
            proxy_pass http://product-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            proxy_pass http://orders-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payments/ {
            proxy_pass http://payment-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cart/ {
            proxy_pass http://cart-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/category/ {
            proxy_pass http://category-backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
