events {}

http {
    upstream frontend {
        server frontend:80;
    }

    upstream user_backend {
        server user_backend:8000;
    }

    upstream product_backend {
        server product_backend:8000;
    }

    upstream order_backend {
        server order_backend:8000;
    }

    upstream payment_backend {
        server payment_backend:8000;
    }

    upstream cart_backend {
        server cart_backend:8000;
    }

    server {
        listen 80;

        # React frontend
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---------- API ROUTES ----------
        location /api/users/ {
            proxy_pass http://user_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/products/ {
            proxy_pass http://product_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/orders/ {
            proxy_pass http://order_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/payments/ {
            proxy_pass http://payment_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cart/ {
            proxy_pass http://cart_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
